### ISSUE TITLE
Buffalo requires go 1.12 rather than 1.10

### ISSUE THREAD

**Issue by spankie** [gobuffalo/docs#469]
![Screen Shot 2019-05-08 at 3 51 43 PM](https://user-images.githubusercontent.com/13089295/57384920-59b5a900-71a9-11e9-937a-4095dcafad0e.png)
I tried creating a new project and this is the error i got... I will have to update my go installation but i just wanted let us know.

**Comment by stanislas-m** [comment]
Thanks, it was updated a while ago. :)
