### ISSUE TITLE
Windows 10 installation error msg="Error: could not find npm executable"

### ISSUE THREAD

**Issue by MarErm27** [gobuffalo/docs#527]
`Microsoft Windows [Version 10.0.18362.476]
(c) 2019 Microsoft Corporation. All rights reserved.

D:\MyProjects\src\github.com\Marat>go get -u github.com/gobuffalo/buffalo/buffalo

D:\MyProjects\src\github.com\Marat>buffalo new coke
[37mDEBU[0m[2019-11-16T23:28:43+03:00] Step: 0e86bb50
[37mDEBU[0m[2019-11-16T23:28:43+03:00] Chdir: D:\MyProjects\src\github.com\Marat\coke
[37mDEBU[0m[2019-11-16T23:28:43+03:00] File: D:\MyProjects\src\github.com\Marat\coke\.codeclimate.yml
[37mDEBU[0m[2019-11-16T23:28:44+03:00] File: D:\MyProjects\src\github.com\Marat\coke\.env
[37mDEBU[0m[2019-11-16T23:28:44+03:00] File: D:\MyProjects\src\github.com\Marat\coke\README.md
[37mDEBU[0m[2019-11-16T23:28:44+03:00] File: D:\MyProjects\src\github.com\Marat\coke\actions\actions_test.go
[37mDEBU[0m[2019-11-16T23:28:44+03:00] File: D:\MyProjects\src\github.com\Marat\coke\actions\app.go
[37mDEBU[0m[2019-11-16T23:28:44+03:00] File: D:\MyProjects\src\github.com\Marat\coke\actions\home.go
[37mDEBU[0m[2019-11-16T23:28:44+03:00] File: D:\MyProjects\src\github.com\Marat\coke\actions\home_test.go
[37mDEBU[0m[2019-11-16T23:28:44+03:00] File: D:\MyProjects\src\github.com\Marat\coke\actions\render.go
[37mDEBU[0m[2019-11-16T23:28:44+03:00] File: D:\MyProjects\src\github.com\Marat\coke\fixtures\sample.toml
[37mDEBU[0m[2019-11-16T23:28:44+03:00] File: D:\MyProjects\src\github.com\Marat\coke\grifts\init.go
[37mDEBU[0m[2019-11-16T23:28:45+03:00] File: D:\MyProjects\src\github.com\Marat\coke\inflections.json
[37mDEBU[0m[2019-11-16T23:28:45+03:00] File: D:\MyProjects\src\github.com\Marat\coke\main.go
[37mDEBU[0m[2019-11-16T23:28:45+03:00] File: D:\MyProjects\src\github.com\Marat\coke\config\buffalo-app.toml
[37mDEBU[0m[2019-11-16T23:28:45+03:00] Step: 1278b9d8
[37mDEBU[0m[2019-11-16T23:28:45+03:00] Chdir: D:\MyProjects\src\github.com\Marat\coke
[37mDEBU[0m[2019-11-16T23:28:45+03:00] File: D:\MyProjects\src\github.com\Marat\coke\.dockerignore
[37mDEBU[0m[2019-11-16T23:28:45+03:00] File: D:\MyProjects\src\github.com\Marat\coke\Dockerfile
[37mDEBU[0m[2019-11-16T23:28:45+03:00] Step: e7a3abbf
[37mDEBU[0m[2019-11-16T23:28:45+03:00] Chdir: D:\MyProjects\src\github.com\Marat\coke
[37mDEBU[0m[2019-11-16T23:28:45+03:00] File: D:\MyProjects\src\github.com\Marat\coke\grifts\db.go
[37mDEBU[0m[2019-11-16T23:28:45+03:00] File: D:\MyProjects\src\github.com\Marat\coke\models\models.go
[37mDEBU[0m[2019-11-16T23:28:45+03:00] File: D:\MyProjects\src\github.com\Marat\coke\models\models_test.go
[37mDEBU[0m[2019-11-16T23:28:45+03:00] Exec: go get github.com/gobuffalo/pop
[37mDEBU[0m[2019-11-16T23:36:38+03:00] Step: 6578da72
[37mDEBU[0m[2019-11-16T23:36:38+03:00] Chdir: D:\MyProjects\src\github.com\Marat\coke
[37mDEBU[0m[2019-11-16T23:36:38+03:00] File: D:/MyProjects/src/github.com/Marat/coke/database.yml
[37mDEBU[0m[2019-11-16T23:36:39+03:00] Step: 1340bdc5
[37mDEBU[0m[2019-11-16T23:36:39+03:00] Chdir: D:\MyProjects\src\github.com\Marat\coke
[37mDEBU[0m[2019-11-16T23:36:39+03:00] File: D:\MyProjects\src\github.com\Marat\coke\.buffalo.dev.yml
[37mDEBU[0m[2019-11-16T23:36:39+03:00] Step: dae2f4c0
[37mDEBU[0m[2019-11-16T23:36:39+03:00] Chdir: D:\MyProjects\src\github.com\Marat\coke
[37mDEBU[0m[2019-11-16T23:36:39+03:00] Exec: go get github.com/gobuffalo/buffalo-pop
[37mDEBU[0m[2019-11-16T23:37:58+03:00] Step: 76f9930b
[37mDEBU[0m[2019-11-16T23:37:58+03:00] Chdir: D:\MyProjects\src\github.com\Marat\coke
[37mDEBU[0m[2019-11-16T23:37:58+03:00] File: D:/MyProjects/src/github.com/Marat/coke/config/buffalo-plugins.toml
[37mDEBU[0m[2019-11-16T23:37:58+03:00] Step: a6edb72e
[37mDEBU[0m[2019-11-16T23:37:58+03:00] Chdir: D:\MyProjects\src\github.com\Marat\coke
[37mDEBU[0m[2019-11-16T23:37:58+03:00] Exec: go get -t ./...
[37mDEBU[0m[2019-11-16T23:38:20+03:00] Step: b1dc18dd
[37mDEBU[0m[2019-11-16T23:38:20+03:00] Chdir: D:\MyProjects\src\github.com\Marat\coke
[37mDEBU[0m[2019-11-16T23:38:20+03:00] File: D:\MyProjects\src\github.com\Marat\coke\actions\app.go
[37mDEBU[0m[2019-11-16T23:38:20+03:00] File: D:\MyProjects\src\github.com\Marat\coke\actions\home.go
[37mDEBU[0m[2019-11-16T23:38:20+03:00] File: D:\MyProjects\src\github.com\Marat\coke\actions\home_test.go
[37mDEBU[0m[2019-11-16T23:38:20+03:00] File: D:\MyProjects\src\github.com\Marat\coke\actions\render.go
[37mDEBU[0m[2019-11-16T23:38:20+03:00] File: D:\MyProjects\src\github.com\Marat\coke\locales\all.en-us.yaml
[37mDEBU[0m[2019-11-16T23:38:20+03:00] File: D:\MyProjects\src\github.com\Marat\coke\public\robots.txt
[37mDEBU[0m[2019-11-16T23:38:20+03:00] File: D:\MyProjects\src\github.com\Marat\coke\templates\_flash.plush.html
[37mDEBU[0m[2019-11-16T23:38:20+03:00] File: D:\MyProjects\src\github.com\Marat\coke\templates\application.plush.html
[37mDEBU[0m[2019-11-16T23:38:20+03:00] File: D:\MyProjects\src\github.com\Marat\coke\templates\index.plush.html
[37mDEBU[0m[2019-11-16T23:38:20+03:00] Step: 07ff9778
[37mDEBU[0m[2019-11-16T23:38:20+03:00] Chdir: D:\MyProjects\src\github.com\Marat\coke
[37mDEBU[0m[2019-11-16T23:38:20+03:00] LookPath: npm
Usage:
  buffalo new [name] [flags]

Flags:
      --api                  skip all front-end code and configure for an API server
      --ci-provider string   specify the type of ci file you would like buffalo to generate [none, travis, gitlab-ci] (default "none")
      --config string        config file (default is $HOME/.buffalo.yaml)
      --db-type string       specify the type of database you want to use [cockroach, mysql, postgres] (default "postgres")
      --docker string        specify the type of Docker file to generate [none, multi, standard] (default "multi")
  -d, --dry-run              dry run
  -f, --force                delete and remake if the app already exists
  -h, --help                 help for new
      --module string        specify the root module (package) name. [defaults to 'automatic']
      --skip-config          skips using the config file
      --skip-pop             skips adding pop/soda to your app
      --skip-webpack         skips adding Webpack to your app
      --skip-yarn            use npm instead of yarn for frontend dependencies management
      --vcs string           specify the Version control system you would like to use [none, git, bzr] (default "git")
  -v, --verbose              verbosely print out the go get commands

time="2019-11-16T23:38:21+03:00" level=error msg="Error: could not find npm executable"

D:\MyProjects\src\github.com\Marat>`

**Comment by kteb** [comment]
As mentionned in https://gobuffalo.io/en/docs/getting-started/installation#requirements you need to have NPM or Yarn is installed. Could you check it is the case ?

**Comment by MarErm27** [comment]
Thank you very much, it just literaly says "could not find npm executable" that helps a lot

**Comment by MarErm27** [comment]
I've tried to verify the installation, but it messaget me with a text below. Am I need to set some variables for buffalo? Like %BUFFALOPATH%
 
'buffalo' is not recognized as an internal or external command,
operable program or batch file.

**Comment by kteb** [comment]
The path where buffalo is installed should be in your main PATH, how did you install Buffalo ?

**Comment by MarErm27** [comment]
I did this https://blog.gobuffalo.io/install-buffalo-on-windows-10-e08b3aa304a3
It is says what I need to do for Windows:
Go to following page: http://tdm-gcc.tdragon.net/
Download the TDM64 bundle
Start the TDM64 bundle and the installer opens
Run again the buffalo installation:
go get -u github.com/gobuffalo/buffalo/buffalo
Ready

**Comment by kteb** [comment]
It's quite an old post. GCC is not needed anymore by default (you need to precise if you want to use sqlite). 

Where is your $GOPATH ? Have you your env variable: $GOPATH/bin installed in your $PATH ?

**Comment by MarErm27** [comment]
My GOPATH is "d:\MyProject"
I've added "%GOPATH%/bin" to my PATH
One possible readon caused buffalo to be not recognized is that after Buffalo installation it didn't appear in "%GOPATH%/bin" folder. 
ScrennShot:
![image](https://user-images.githubusercontent.com/56219126/70212014-951c5400-1747-11ea-989b-79bdfc59acf9.png)

**Comment by kteb** [comment]
Try to go in a shell in %GOPATH%\src\github.com\gobuffalo\buffalo\buffalo 

and there type `go install`

**Comment by MarErm27** [comment]
THANK YOU VERY MUCH!!!!! It is helped a lot!

**Comment by kteb** [comment]
It worked ?

**Comment by MarErm27** [comment]
Yes, screen shot:
![image](https://user-images.githubusercontent.com/56219126/70299529-32d65880-1806-11ea-9319-b28ba4d15688.png)

I've got one more question, Buffalo is not going to support GOPATH anymore, but some libraries do not support modules. For me as a completely newbie is it beter to stay with gopath or it's beter to start my app with modules?

**Comment by kteb** [comment]
I will recommend (but it's a personal opinion) to go with modules, more and more existing will migrate to modules, even if people are refracted to changes, module bring a lot of interesting features. And if people will migrate to modules, or people will fork them to have modules supported. At least it's my opinion.

**Comment by MarErm27** [comment]
Thank you very much! How to close this issue?

**Comment by kteb** [comment]
Simply by clicking on Close issue under the box where you leave a comment (at least on a pc)
