### ISSUE TITLE
No z-index on documentation

### ISSUE THREAD

**Issue by bjvanbemmel** [gobuffalo/docs#604]
You can enable horizontal scroll by selecting the commands all the way in the documentation. Doing so leads to multiple objects appearing above the side bar. View Imgur link to see results or reproduce by making the window smaller and selecting a long(er) command inside the documentation.

https://imgur.com/a/5MO8ame

**Comment by paganotoni** [comment]
Closing this one as it may no longer be relevant. Thanks 
@bjvanbemmel for reporting it.
