### ISSUE TITLE
Docs: Events page is 404-ing

### ISSUE THREAD

**Issue by preslavrachev** [gobuffalo/docs#636]
I was incredibly happy to see the redesign of the docs. I want to congratulate you all on this achievement!

As I was googling for how to use the `events` package, I ended up to this page: https://gobuffalo.io/en/docs/events - previously, it would show up some documentation, but currently, it returns a straight 404. 

Is this something that might have slipped away with the many recent changes, or was it intentional not to include it in future revisions of the docs?

**Comment by paganotoni** [comment]
Thanks for the heads up @preslavrachev, we're working on those.

**Comment by preslavrachev** [comment]
@sio4 @paganotoni Great! Thank you, guys and sorry for posting in the wrong repo 😅

**Comment by sio4** [comment]
No problem! I do the same 🤪
