### ISSUE TITLE
Incorrect link for install Buffalo CLI

### ISSUE THREAD

**Issue by grahamschock** [gobuffalo/docs#638]
Hi,

I noticed a broken link in http://gobuffalo.io/documentation/getting_started/installation/
https://github.com/gobuffalo/docs/blob/main/content/documentation/getting_started/installation.md?plain=1#L65

```bash
$ wget https://github.com/gobuffalo/cli/releases/download/v0.18.3/buffalo_v0.18.3_Linux_x86_64.tar.gz
...
HTTP request sent, awaiting response... 404 Not Found
```
It looks like it should be (without the v in the .tar.gz file name): 

```bash
wget https://github.com/gobuffalo/cli/releases/download/v0.18.3/buffalo_0.18.3_Linux_x86_64.tar.gz
...
HTTP request sent, awaiting response... 200 OK
```
It looks like this line should not have the same `{{< latestclirelease >}}` variable:

**Comment by paganotoni** [comment]
Thanks for reporting this one @grahamschock

**Comment by grahamschock** [comment]
It looks like the installation command was only partially updated so the tar command still references the incorrect .tar.gz file.

**Comment by paganotoni** [comment]
Thanks for the PR @grahamschock! I think this one is solved now. Can you confirm?
